### ISSUE TITLE
hover on macro variables (#xxxx)  to show description of it

### ISSUE THREAD

**Issue by Suraissa** [jmr1/vscode-ncproj#2]
First thank you for the extension. It works great.

Just one small question: would it be able to show the description of the macro variables when hovering on it? currently it displays the current value of the variables on hover. 

We have a lot of macros for various machines and used a large amount of system variables or common variables in the macros. Each time when we edit or view a macro,  we have to search the manual for the meaning of the variables. It's really a pain. It would be a great help if we could somehow check the description of the variables within Vscode. 

Thank you.

**Comment by jmr1** [comment]
Thanks for the good word.

By system variables do you mean for example Fanuc system macro variables like shown below? https://www.machinetoolhelp.com/Applications/macro/system_variables.html

And what do you mean by common variables? It's another name for system variables or perhaps user defined variables?

**Comment by Suraissa** [comment]
yes.

local variable: #1 - #33
common variable ( user defined global variable) : #100 -#999
system variable: #1000 +
